name: diag

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Update version.js
        run: |
          echo "self.__BUILD='${SHORT_SHA}';" > version.js
          cat version.js

      - name: Commit and push version.js
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.js
          git commit -m "chore: bump build version to ${SHORT_SHA}" || echo "No changes to commit"
          git push

      - name: Show diagnostics
        run: |
          echo "Build version: ${SHORT_SHA}"
          echo "Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
